apiVersion: v1
kind: Service
metadata:
  name: log-producer-svc
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30101
  selector:
    app: log-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-producer
  template:
    metadata:
      labels:
        app: log-producer
    spec:
      containers:
        - name: log-producer
          image: log-producer:k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCER_PORT
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCER_KAFKA_BROKER
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PRODUCER_KAFKA_TOPIC